name: Check sketch

on:
 workflow_dispatch:
 push:

jobs:

  # Compile code

  compile:

    runs-on: macos-latest
    
    steps:

      # Clone repository
      
      - name: Clone repository
        uses: actions/checkout@main

      # Setup arduino CLI
      
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@master

      # Configure platform
      
      - name: Configure platform
        run: |
          arduino-cli config init 
          arduino-cli config set library.enable_unsafe_install true
          arduino-cli core install arduino:megaavr
          arduino-cli lib install "Adafruit NeoPixel"
          arduino-cli lib install --git-url https://github.com/me-no-dev/ESPAsyncWebServer.git https://github.com/me-no-dev/ESPAsyncTCP.git
          
      # Compile
      
      - name: Compile sketch
        run: |
          arduino-cli compile -b "arduino:megaavr:nona4809:mode=off" -e ./sketch